version: '3.7'
services:
  riws-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: riws-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node  
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=riwspractica
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.enabled=false  # Disable security
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
  python-server:
    image: danielsilvai/riws-python-fastapi:beta
    container_name: riws-python-server
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - riws-elasticsearch
    networks:
      - esnet
  angular-frontend:
    image: danielsilvai/riws-angular-web:beta
    container_name: riws-angular-frontend
    restart: unless-stopped
    ports:
      - 4200:80
    expose:
      - "4200"
    networks:
      - esnet
  elastic-setup:
    image: danielsilvai/riws-elastic-setup:beta
    container_name: riws-elastic-setup
    depends_on:
      - riws-elasticsearch
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:

# reference -> https://discuss.elastic.co/t/set-password-and-user-with-docker-compose/225075
