version: '3.7'
services:
  riws-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: riws-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node  
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=riwspractica
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.enabled=false  # Disable security
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

networks:
  esnet:

# reference -> https://discuss.elastic.co/t/set-password-and-user-with-docker-compose/225075
